### ISSUE TITLE
Consider adding option to save the history of prompts and answers, together with system information

### ISSUE THREAD

**Issue by maxim-uvarov** [kharvd/gpt-cli#12]
I believe it could be useful to have a local log, such as YAML files, to be able to skim through past conversations.

In this way, it would allow for scripting possibilities with chats from other tools.

P.S. Thank you for the handy tool! I am using it with great pleasure!

**Comment by kharvd** [comment]
There already is a log: you can turn it on by passing `--log_file` command line argument or adding 
```yaml
log_file: path/to/file.log
```
to your `~/.gptrc`. This is not well documented at the moment, but sounds like we should add some info about this.

**Comment by itsFrank** [comment]
I got here looking for a way to save a conversation as proper markdown for reference later. The log_file hint was great and I ended up building a little util that cleans up the log, enhances it for readability, and saves it as a new file.

Util can be found here: https://github.com/itsFrank/save-gpt-cli

disclosure: chat GPT wrote most of the code.

**Comment by fernandovmacedo** [comment]
I was also interested in browsing my prompt history and wrote a quick bash script. It is just a call to `ripgrep` that strips the logging data and puts simple markdown headers.

https://gist.github.com/fernandovmacedo/9d9c6b8928bc6b7929446127c2ee07a0
