### ISSUE TITLE
How to use multi-line mode?

### ISSUE THREAD

**Issue by raine** [kharvd/gpt-cli#20]
Hey there.

> To enter multi-line mode, enter a backslash \ followed by a new line. 

```
% python3 ./gpt.py
Hi! I'm here to help. Type q or Ctrl-D to exit, c or Ctrl-C to clear the
conversation, r or Ctrl-R to re-generate the last response. To enter multi-line
mode, enter a backslash \ followed by a new line. Exit the multi-line mode by
pressing ESC and then Enter (Meta+Enter).
> Hello world \
Hello! How can I assist you today?
```

What am I doing wrong? Thanks.

**Comment by gAbelli** [comment]
If I understand correctly, at the moment you need to input just a `\` to enter multiline mode, and then start typing. It's something like this:

```
> \
multiline> Hello world
```

I agree that it is not very intuitive, maybe it could be changed in the future.

**Comment by raine** [comment]
Ah, I was thinking it would work like `\` in shell.

```
$ echo foo \
> bar \
> xyz
foo bar xyz
```

Thanks for explaining.
