### ISSUE TITLE
Quotas exceeded ?

### ISSUE THREAD

**Issue by fredleger** [kharvd/gpt-cli#27]
Hi, got a strange behavior

## error

```
(.venv) ➜  gpt-cli git:(main) ./gpt.py
Hi! I'm here to help. Type q or Ctrl-D to exit, c or Ctrl-C to clear the
conversation, r or Ctrl-R to re-generate the last response. To enter multi-line
mode, enter a backslash \ followed by a new line. Exit the multi-line mode by
pressing ESC and then Enter (Meta+Enter).
> something fun

API Error. Type `r` or Ctrl-R to try again: <class 'openai.error.RateLimitError'>: You exceeded your current quota, please check your plan and billing details.
You exceeded your current quota, please check your plan and billing details.
Traceback (most recent call last):
  File "/Users/frederic/bin/gpt-cli/gptcli/session.py", line 96, in _respond
    for response in completion_iter:
  File "/Users/frederic/bin/gpt-cli/gptcli/openai.py", line 20, in complete
    openai.ChatCompletion.create(
  File "/Users/frederic/bin/gpt-cli/.venv/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/frederic/bin/gpt-cli/.venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/frederic/bin/gpt-cli/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/frederic/bin/gpt-cli/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/Users/frederic/bin/gpt-cli/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
```

## usage screenshot
![image](https://user-images.githubusercontent.com/2778741/236480221-dd318fce-0ea0-4409-a2bb-ac98687c666d.png)

## notes

i'm using free plan but i don't see any limitation mentioned about it

**Comment by KaueSabinoSRV17** [comment]
I also received this error recently. It's not entirely clear what the limitations are for the OpenAI API's free plan. When I asked ChatGPT how long I would need to wait to make another request after exceeding my quota, I received the following response:

## Response From ChatGPT

![image](https://user-images.githubusercontent.com/81828528/236484422-fccd558a-729e-4cce-8538-16371eac44bf.png)

## Possible Cause of the Problem

I'm not sure how you are using the API, but I ran into a similar issue when I was working on a project that involved looping through a data source and making a request to the API in each iteration. This likely consumed a significant portion of my API quota.

**Comment by fredleger** [comment]
@KaueSabinoSRV17 thanks for looking on this.
i just never connected to the open API so it might not be the root cause :-)

**Comment by KaueSabinoSRV17** [comment]
Alright. it might be the CLI usage, which is totally believable. 4000 is a very low rate limit for the CLI.

**Comment by fredleger** [comment]
@KaueSabinoSRV17 but never used the cli for openapi ... 1s time

**Comment by KaueSabinoSRV17** [comment]
That's very unfortunate.

I suggest, if you can, that you edit you Issue's title to "Quotas exceded even without ever using Openai API". Unfortunally i dont have permissions to alter that kind of stuff or prioritaze issues

**Comment by kharvd** [comment]
I don't think your issue is related to the project. Looks like your free credits expired and you need to connect a credit card or something.
