### ISSUE TITLE
Loading historical commands on start

### ISSUE THREAD

**Issue by rguerrettaz** [kharvd/gpt-cli#28]
Wondering if we could easily load previous session chat prompts on start - i.e. session history. This would allow you to up arrow and choose a command you ran in a recent session. Not a huge deal if it's a lot of work.  Thanks for this library!

**Comment by kharvd** [comment]
Great suggestion, this is pretty easy, I'll put up a PR.

**Comment by rguerrettaz** [comment]
Thank you! :godmode:
