### ISSUE TITLE
Proposal: support more terminal keyboard commands

### ISSUE THREAD

**Issue by rguerrettaz** [kharvd/gpt-cli#36]
Loving the CLI tool and one thing I keep finding myself doing out of habit is using terminal keyboard commands like:

* `option` + `arrow` (move forward or back a word)
* `option` + `delete` (delete the previous word)
* `ctrl` + `e` (go to end of line)
* `ctrl` + `a` (go to beginning of line) 
* `ctrl` + `u` (delete entire line)

Unsure if listening to these commands is an easy addition, but if so it would be really nice as it more closely mirrors the terminal experience. 

Thanks again!

**Comment by kharvd** [comment]
Fixed by #47
