### ISSUE TITLE
add try-agagin func to solve speed rate limit in claude

### ISSUE THREAD

**Issue by moxi000** [kharvd/gpt-cli#38]
when I use claude api, always return
anthropic.api.ApiException: ('post request failed with status code: 429', {'error': {'type': 'rate_limit_error', 'message': 'Number of concurrent connections to Claude exceeds your rate limit. Please try again, or contact sales@anthropic.com to discuss your options for a rate limit increase.'}})
then the process will be killed(end)

**Comment by kharvd** [comment]
Try Ctrl-R or `rerun`
