### ISSUE TITLE
Can conversations be restored?

### ISSUE THREAD

**Issue by TimDaub** [kharvd/gpt-cli#43]
E.g. right now I had a conversation of 4k tokens with gpt4 and I accidentally did a Ctrl-c and cleared the conversation, but that was an accident. Is there any way to undo this? Or load that conversation again?

**Comment by kharvd** [comment]
No way to directly undo this, unfortunately. As a workaround, if you saved the logs, you can restore the conversation manually by setting up a separate `assistant` with the messages from the previous conversation (see the README for the format)

**Comment by TimDaub** [comment]
do u have this on the roadmap? It feels like a deal breaker. I had it already a couple of times that I then accidentially do ctrl c and everything is gone

maybe ask to confirm with (y|n) fixes 99% of issues in that regard

**Comment by kharvd** [comment]
Would it help if the shortcut to stop producing a response was different from clearing the conversation?

**Comment by TimDaub** [comment]
I think ctrl c is too dangerous to delete the entire conversation. I hit it very often, e.g. yes, when I stop producing the response but also in general in the terminal I hit it quite a lot and e.g. in tmux I move around with the cursor so I may also hit it accidentally. I honestly wouldn't mind if I had to confirm clearing the conversation I think. Somehow I find it quite natural that ctrl c also clears the conversation

**Comment by kharvd** [comment]
Made Ctrl+C just paste `:clear` instead of clearing immediately https://github.com/kharvd/gpt-cli/pull/48
