### ISSUE TITLE
Any way to run local llms with this? 

### ISSUE THREAD

**Issue by adiso06** [kharvd/gpt-cli#67]
Not sure how to direct this to a local llm rather than OpenAi or claude

**Comment by kharvd** [comment]
Use OPENAI_BASE_URL and a local REST API, e.g. with ollama or lmstudio

https://github.com/ollama/ollama?tab=readme-ov-file#rest-api
https://github.com/kharvd/gpt-cli?tab=readme-ov-file#customize-openai-api-url
