### ISSUE TITLE
"Server Overloaded" message at Anthropic breaks sessions often with 'uncaught exception'

### ISSUE THREAD

**Issue by RanTrycl** [kharvd/gpt-cli#71]
When the servers are overloaded at Anthropic:
```

`anthropic.APIStatusError: {'type': 'error', 'error': {'details': None, 'type': 'overloaded_error', 'message': 'Overloaded'}}
`
```
They send back an error, sometimes 529, sometimes nothing, leading to this:

```
anthropic.APIStatusError: {'type': 'error', 'error': {'details': None, 'type': 'overloaded_error', 'message': 'Overloaded'}}
An uncaught exception occurred. Please report this issue on GitHub.
Traceback (most recent call last):
  File "/home/gnewt/.pyenv/versions/3.12-dev/bin/gpt", line 8, in <module>
    sys.exit(main())
```

this crashes the session and eliminates Claude's memory. Can the script be changed to tolerate a "server overloaded" message without breaking? These errors are pretty common.

**Comment by janacm** [comment]
From Anthropic:

Error events
We may occasionally send [errors](https://docs.anthropic.com/en/api/errors) in the event stream. For example, during periods of high usage, you may receive an overloaded_error, which would normally correspond to an HTTP 529 in a non-streaming context:

See: https://docs.anthropic.com/en/api/messages-streaming
