### ISSUE TITLE
include openai o1 models

### ISSUE THREAD

**Issue by williamjameshandley** [kharvd/gpt-cli#90]
[openai](https://openai.com/index/introducing-openai-o1-preview/) released its o1 'reasoning' models this week. It would be great to incorporate these.

I think that this is relatively straightforward (suggested PR: #89 modelled on this commit https://github.com/kharvd/gpt-cli/commit/d90b1b96c1630dccf6c971ceed4e78bf59d902e9), but it does open some interesting questions for more fine-grained pricing reports. The new models now provide information for [how many tokens were used for reasoning](https://platform.openai.com/docs/guides/reasoning/managing-the-context-window) in the `completion_tokens_details`.

**Comment by kharvd** [comment]
fixed in #89
